include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
    - "test/.test_coverage.dart"
    - "coverage/**"
  
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore
    unused_import: warning
    unused_local_variable: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    avoid_print: warning
    avoid_dynamic_calls: warning
    avoid_empty_else: error
    avoid_relative_lib_imports: warning
    avoid_returning_null_for_future: error
    avoid_slow_async_io: warning
    avoid_types_as_parameter_names: warning
    await_only_futures: error
    cancel_subscriptions: error
    close_sinks: warning
    constant_identifier_names: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    empty_statements: warning
    hash_and_equals: warning
    implementation_imports: warning
    no_duplicate_case_values: error
    non_constant_identifier_names: warning
    null_closures: warning
    prefer_contains: warning
    prefer_final_fields: warning
    prefer_final_locals: warning
    prefer_if_null_operators: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_new: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_this: warning
    unrelated_type_equality_checks: error
    use_key_in_widget_constructors: warning
    use_rethrow_when_possible: warning
    valid_regexps: warning
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - prefer_contains
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_late_for_private_fields_when_needed
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - valid_regexps