name: flutter_ecommerce_app
description: Aplicación de comercio electrónico con arquitectura limpia y pruebas BDD.

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.2
  dartz: ^0.10.1
  http: ^1.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  gherkin: ^latest
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - test/fixtures/products.json
    - test/fixtures/transaction.json

  # Configuración para pruebas BDD
  gherkin:
    features:
      - test/bdd/features/
    stepDefinitions:
      - test/bdd/step_definitions/
    testHelpers:
      - test/bdd/test_helpers.dart